name: Build Flet App
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build APK
        run: |
          pip install flet==0.24.0
          # Создаем файл настроек прямо перед сборкой
          echo 'app:
            name: "Dolphin"
            icon: "icon.png"' > flet.yaml
          # Теперь вызываем сборку без аргументов, он сам подхватит flet.yaml
          flet build apk
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Dolphin-APK
          path: build/apk/app-release.apk
